name = "vetuonglai-edu-github"
main = "src/index.js"
compatibility_date = "2026-02-03"
compatibility_flags = ["nodejs_compat"]

account_id = "f3f9e76222dcb488d5e303e29e8ba192"

kv_namespaces = [
  { binding = "EDU_DB", id = "261d518acbd64691a48f1cfaf26ded4b" }
]

r2_buckets = [
  { binding = "EDU_DOCS",  bucket_name = "edu-docs" },
  { binding = "EDU_MEDIA", bucket_name = "edu-media" }
]
