name = "vetuonglai-edu-github"
main = "src/index.js"
compatibility_date = "2026-02-05"

# KV: chỉ giữ EDU_DB
kv_namespaces = [
  { binding = "EDU_DB", id = "261d518acbd64691a48f1cfaf26ded4b" }
]

# R2: bucket_name phải là tên bucket thật (lowercase + hyphen)
r2_buckets = [
  { binding = "EDU_DOCS", bucket_name = "edu-docs" },
  { binding = "EDU_MEDIA", bucket_name = "edu-media" }
]
