name = "vetuonglai-edu-github"
main = "src/index.js"
compatibility_date = "2024-12-01"
workers_dev = true

[vars]
APP_ORIGIN = "https://edu.vetuonglai.com"
MAGIC_TTL_MIN = "15"
MAIL_FROM = "reply@vetuonglai.com"

[[kv_namespaces]]
binding = "EDU_DB"
id = "REPLACE_WITH_YOUR_EDU_DB_KV_ID"

[[r2_buckets]]
binding = "EDU_DOCS"
bucket_name = "EDU_DOCS"

[[r2_buckets]]
binding = "EDU_MEDIA"
bucket_name = "EDU_MEDIA"
